/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "client_prot.h"

bool_t
xdr_client_up_arg (XDR *xdrs, client_up_arg *objp)
{

	 if (!xdr_string (xdrs, &objp->handle, ~0))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->generation.generation_val, (u_int *) &objp->generation.generation_len, ~0,
		sizeof (uint32_t), (xdrproc_t) xdr_uint32_t))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->client_tag))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_client_down_arg (XDR *xdrs, client_down_arg *objp)
{

	 if (!xdr_string (xdrs, &objp->handle, ~0))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->generation.generation_val, (u_int *) &objp->generation.generation_len, ~0,
		sizeof (uint32_t), (xdrproc_t) xdr_uint32_t))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->layer_status))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->killed))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->would_kill))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->client_tag))
		 return FALSE;
	return TRUE;
}
