/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DSM_H_RPCGEN
#define _DSM_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


typedef uint32_t dsm_count;

#define DSM_PROG 482633
#define DSM_VERS1 1

#if defined(__STDC__) || defined(__cplusplus)
#define DSM_NULL 0
extern  enum clnt_stat dsm_null_1(void *, void *, CLIENT *);
extern  bool_t dsm_null_1_svc(void *, void *, struct svc_req *);
#define DSM_INC 1
extern  enum clnt_stat dsm_inc_1(void *, dsm_count *, CLIENT *);
extern  bool_t dsm_inc_1_svc(void *, dsm_count *, struct svc_req *);
#define DSM_COUNT 2
extern  enum clnt_stat dsm_count_1(void *, dsm_count *, CLIENT *);
extern  bool_t dsm_count_1_svc(void *, dsm_count *, struct svc_req *);
extern int dsm_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DSM_NULL 0
extern  enum clnt_stat dsm_null_1();
extern  bool_t dsm_null_1_svc();
#define DSM_INC 1
extern  enum clnt_stat dsm_inc_1();
extern  bool_t dsm_inc_1_svc();
#define DSM_COUNT 2
extern  enum clnt_stat dsm_count_1();
extern  bool_t dsm_count_1_svc();
extern int dsm_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_dsm_count (XDR *, dsm_count*);

#else /* K&R C */
extern bool_t xdr_dsm_count ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DSM_H_RPCGEN */
