/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "dsm.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
dsm_null_1(void *argp, void *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, DSM_NULL,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
dsm_inc_1(void *argp, dsm_count *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, DSM_INC,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_dsm_count, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
dsm_count_1(void *argp, dsm_count *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, DSM_COUNT,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_dsm_count, (caddr_t) clnt_res,
		TIMEOUT));
}
