// -*-c++-*-
/* This file was automatically generated by rpcc. */

#include "rep.h"

#ifdef MAINTAINER

void
print_mid_t (const void *_objp, const strbuf *_sbp, int _recdepth,
             const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const mid_t *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_mid_t (const mid_t *objp)
{
  rpc_print (warnx, *objp);
}

void
print_rid_t (const void *_objp, const strbuf *_sbp, int _recdepth,
             const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const rid_t *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_rid_t (const rid_t *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const viewid_t &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "viewid_t " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.counter, recdepth, "counter", npref);
  sb << sep;
  rpc_print (sb, obj.manager, recdepth, "manager", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_viewid_t (const void *_objp, const strbuf *_sbp, int _recdepth,
                const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const viewid_t *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_viewid_t (const viewid_t *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const net_address_t &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "net_address_t " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.ipaddr, recdepth, "ipaddr", npref);
  sb << sep;
  rpc_print (sb, obj.port, recdepth, "port", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_net_address_t (const void *_objp, const strbuf *_sbp, int _recdepth,
                     const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const net_address_t *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_net_address_t (const net_address_t *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const cohort_t &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "cohort_t " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.mid, recdepth, "mid", npref);
  sb << sep;
  rpc_print (sb, obj.addr, recdepth, "addr", npref);
  sb << sep;
  rpc_print (sb, obj.name, recdepth, "name", npref);
  sb << sep;
  rpc_print (sb, obj.hypervisor, recdepth, "hypervisor", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_cohort_t (const void *_objp, const strbuf *_sbp, int _recdepth,
                const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const cohort_t *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_cohort_t (const cohort_t *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const execute_viewinfo &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "execute_viewinfo " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.vid, recdepth, "vid", npref);
  sb << sep;
  rpc_print (sb, obj.primary, recdepth, "primary", npref);
  sb << sep;
  rpc_print (sb, obj.primary_c, recdepth, "primary_c", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_execute_viewinfo (const void *_objp, const strbuf *_sbp, int _recdepth,
                        const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const execute_viewinfo *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_execute_viewinfo (const execute_viewinfo *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const execute_arg &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "execute_arg " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.client, recdepth, "client", npref);
  sb << sep;
  rpc_print (sb, obj.rid, recdepth, "rid", npref);
  sb << sep;
  rpc_print (sb, obj.vid, recdepth, "vid", npref);
  sb << sep;
  rpc_print (sb, obj.request, recdepth, "request", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_execute_arg (const void *_objp, const strbuf *_sbp, int _recdepth,
                   const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const execute_arg *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_execute_arg (const execute_arg *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const execute_res &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "execute_res " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.ok, recdepth, "ok", npref);
  switch (obj.ok) {
  case true:
    sb << sep;
    rpc_print (sb, *obj.reply,  recdepth, "reply", npref);
    break;
  case false:
    sb << sep;
    rpc_print (sb, *obj.viewinfo,  recdepth, "viewinfo", npref);
    break;
  default:
    break;
  }
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_execute_res (const void *_objp, const strbuf *_sbp, int _recdepth,
                   const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const execute_res *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_execute_res (const execute_res *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const view_t &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "view_t " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.vid, recdepth, "vid", npref);
  sb << sep;
  rpc_print (sb, obj.primary, recdepth, "primary", npref);
  sb << sep;
  rpc_print (sb, obj.backups, recdepth, "backups", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_view_t (const void *_objp, const strbuf *_sbp, int _recdepth,
              const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const view_t *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_view_t (const view_t *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const viewstamp_t &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "viewstamp_t " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.vid, recdepth, "vid", npref);
  sb << sep;
  rpc_print (sb, obj.ts, recdepth, "ts", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_viewstamp_t (const void *_objp, const strbuf *_sbp, int _recdepth,
                   const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const viewstamp_t *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_viewstamp_t (const viewstamp_t *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const replicate_arg &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "replicate_arg " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.vs, recdepth, "vs", npref);
  sb << sep;
  rpc_print (sb, obj.arg, recdepth, "arg", npref);
  sb << sep;
  rpc_print (sb, obj.committed, recdepth, "committed", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_replicate_arg (const void *_objp, const strbuf *_sbp, int _recdepth,
                     const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const replicate_arg *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_replicate_arg (const replicate_arg *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const replicate_res &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "replicate_res " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.vs, recdepth, "vs", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_replicate_res (const void *_objp, const strbuf *_sbp, int _recdepth,
                     const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const replicate_res *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_replicate_res (const replicate_res *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const view_change_arg &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "view_change_arg " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.oldview, recdepth, "oldview", npref);
  sb << sep;
  rpc_print (sb, obj.newvid, recdepth, "newvid", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_view_change_arg (const void *_objp, const strbuf *_sbp, int _recdepth,
                       const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const view_change_arg *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_view_change_arg (const view_change_arg *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const view_change_reject &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "view_change_reject " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.oldview, recdepth, "oldview", npref);
  sb << sep;
  rpc_print (sb, obj.newvid, recdepth, "newvid", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_view_change_reject (const void *_objp, const strbuf *_sbp, int _recdepth,
                          const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const view_change_reject *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_view_change_reject (const view_change_reject *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const view_change_accept &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "view_change_accept " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.myid, recdepth, "myid", npref);
  sb << sep;
  rpc_print (sb, obj.include_me, recdepth, "include_me", npref);
  sb << sep;
  rpc_print (sb, obj.latest, recdepth, "latest", npref);
  sb << sep;
  rpc_print (sb, obj.newview, recdepth, "newview", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_view_change_accept (const void *_objp, const strbuf *_sbp, int _recdepth,
                          const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const view_change_accept *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_view_change_accept (const view_change_accept *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const view_change_res &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "view_change_res " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.accepted, recdepth, "accepted", npref);
  switch (obj.accepted) {
  case false:
    sb << sep;
    rpc_print (sb, *obj.reject,  recdepth, "reject", npref);
    break;
  case true:
    sb << sep;
    rpc_print (sb, *obj.accept,  recdepth, "accept", npref);
    break;
  default:
    break;
  }
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_view_change_res (const void *_objp, const strbuf *_sbp, int _recdepth,
                       const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const view_change_res *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_view_change_res (const view_change_res *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const new_view_arg &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "new_view_arg " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.latest, recdepth, "latest", npref);
  sb << sep;
  rpc_print (sb, obj.view, recdepth, "view", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_new_view_arg (const void *_objp, const strbuf *_sbp, int _recdepth,
                    const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const new_view_arg *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_new_view_arg (const new_view_arg *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const new_view_res &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "new_view_res " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.accepted, recdepth, "accepted", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_new_view_res (const void *_objp, const strbuf *_sbp, int _recdepth,
                    const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const new_view_res *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_new_view_res (const new_view_res *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const view_form_t &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "view_form_t " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.prev, recdepth, "prev", npref);
  sb << sep;
  rpc_print (sb, obj.view, recdepth, "view", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_view_form_t (const void *_objp, const strbuf *_sbp, int _recdepth,
                   const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const view_form_t *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_view_form_t (const view_form_t *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const ping_arg &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "ping_arg " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.myid, recdepth, "myid", npref);
  sb << sep;
  rpc_print (sb, obj.vid, recdepth, "vid", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_ping_arg (const void *_objp, const strbuf *_sbp, int _recdepth,
                const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const ping_arg *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_ping_arg (const ping_arg *objp)
{
  rpc_print (warnx, *objp);
}

const strbuf &
rpc_print (const strbuf &sb, const ping_res &obj, int recdepth,
           const char *name, const char *prefix)
{
  if (name) {
    if (prefix)
      sb << prefix;
    sb << "ping_res " << name << " = ";
  };
  const char *sep;
  str npref;
  if (prefix) {
    npref = strbuf ("%s  ", prefix);
    sep = "";
    sb << "{\n";
  }
  else {
    sep = ", ";
    sb << "{ ";
  }
  rpc_print (sb, obj.ok, recdepth, "ok", npref);
  if (prefix)
    sb << prefix << "};\n";
  else
    sb << " }";
  return sb;
}
void
print_ping_res (const void *_objp, const strbuf *_sbp, int _recdepth,
                const char *_name, const char *_prefix)
{
  rpc_print (_sbp ? *_sbp : warnx, *static_cast<const ping_res *> (_objp),
             _recdepth, _name, _prefix);
}
void
dump_ping_res (const ping_res *objp)
{
  rpc_print (warnx, *objp);
}

#endif /* MAINTAINER*/
void *
mid_t_alloc ()
{
  return New mid_t;
}
bool_t
xdr_mid_t (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<mid_t *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<mid_t *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
rid_t_alloc ()
{
  return New rid_t;
}
bool_t
xdr_rid_t (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<rid_t *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<rid_t *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
viewid_t_alloc ()
{
  return New viewid_t;
}
bool_t
xdr_viewid_t (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<viewid_t *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<viewid_t *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
net_address_t_alloc ()
{
  return New net_address_t;
}
bool_t
xdr_net_address_t (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<net_address_t *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<net_address_t *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
cohort_t_alloc ()
{
  return New cohort_t;
}
bool_t
xdr_cohort_t (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<cohort_t *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<cohort_t *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
execute_viewinfo_alloc ()
{
  return New execute_viewinfo;
}
bool_t
xdr_execute_viewinfo (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<execute_viewinfo *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<execute_viewinfo *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
execute_arg_alloc ()
{
  return New execute_arg;
}
bool_t
xdr_execute_arg (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<execute_arg *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<execute_arg *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
execute_res_alloc ()
{
  return New execute_res;
}
bool_t
xdr_execute_res (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<execute_res *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<execute_res *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
view_t_alloc ()
{
  return New view_t;
}
bool_t
xdr_view_t (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<view_t *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<view_t *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
viewstamp_t_alloc ()
{
  return New viewstamp_t;
}
bool_t
xdr_viewstamp_t (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<viewstamp_t *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<viewstamp_t *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
replicate_arg_alloc ()
{
  return New replicate_arg;
}
bool_t
xdr_replicate_arg (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<replicate_arg *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<replicate_arg *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
replicate_res_alloc ()
{
  return New replicate_res;
}
bool_t
xdr_replicate_res (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<replicate_res *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<replicate_res *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
view_change_arg_alloc ()
{
  return New view_change_arg;
}
bool_t
xdr_view_change_arg (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<view_change_arg *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<view_change_arg *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
view_change_reject_alloc ()
{
  return New view_change_reject;
}
bool_t
xdr_view_change_reject (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<view_change_reject *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<view_change_reject *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
view_change_accept_alloc ()
{
  return New view_change_accept;
}
bool_t
xdr_view_change_accept (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<view_change_accept *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<view_change_accept *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
view_change_res_alloc ()
{
  return New view_change_res;
}
bool_t
xdr_view_change_res (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<view_change_res *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<view_change_res *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
new_view_arg_alloc ()
{
  return New new_view_arg;
}
bool_t
xdr_new_view_arg (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<new_view_arg *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<new_view_arg *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
new_view_res_alloc ()
{
  return New new_view_res;
}
bool_t
xdr_new_view_res (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<new_view_res *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<new_view_res *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
view_form_t_alloc ()
{
  return New view_form_t;
}
bool_t
xdr_view_form_t (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<view_form_t *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<view_form_t *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
ping_arg_alloc ()
{
  return New ping_arg;
}
bool_t
xdr_ping_arg (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<ping_arg *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<ping_arg *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

void *
ping_res_alloc ()
{
  return New ping_res;
}
bool_t
xdr_ping_res (XDR *xdrs, void *objp)
{
  switch (xdrs->x_op) {
  case XDR_ENCODE:
  case XDR_DECODE:
    return rpc_traverse (xdrs, *static_cast<ping_res *> (objp));
  case XDR_FREE:
    rpc_destruct (static_cast<ping_res *> (objp));
    return true;
  default:
    panic ("invalid xdr operation %d\n", xdrs->x_op);
  }
}

static const rpcgen_table rep_prog_1_tbl[] = {
  REP_PROG_1_APPLY (XDRTBL_DECL)
};
const rpc_program rep_prog_1 = {
  REP_PROG, REP_V1, rep_prog_1_tbl,
  sizeof (rep_prog_1_tbl) / sizeof (rep_prog_1_tbl[0]),
  "rep_prog_1"
};

static const rpcgen_table rep_bcast_prog_1_tbl[] = {
  REP_BCAST_PROG_1_APPLY (XDRTBL_DECL)
};
const rpc_program rep_bcast_prog_1 = {
  REP_BCAST_PROG, REP_BCAST_V1, rep_bcast_prog_1_tbl,
  sizeof (rep_bcast_prog_1_tbl) / sizeof (rep_bcast_prog_1_tbl[0]),
  "rep_bcast_prog_1"
};


